version: '2'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - .:/code
    restart: unless-stopped
    depends_on:
     - db
  db:
    image: postgres
    restart: unless-stopped